### Get hourly forecast
GET https://api.open-meteo.com/v1/forecast?latitude=15.47&longitude=47.56&hourly=precipitation,relative_humidity_2m,temperature_2m&forecast_days=1&forecast_hours=12

### Get daily forecast 
GET https://api.open-meteo.com/v1/forecast?latitude=15.47&longitude=47.56&daily=temperature_2m_max,temperature_2m_min
